# Generated by Django 5.2.5 on 2025-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reclamation_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='custom_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reclamation_photos/'),
        ),
    ]
