# Generated by Django 5.2.5 on 2025-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reclamation_custom_type_reclamation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='rating_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
